version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://root:root@db/dev
    command: puma -C config/puma.rb
    # command: tail -f /dev/null

  sidekiq:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
